export const departmentList = [
  { department: '사회과학대', departmentName: 'SOCIAL' },
  { department: '경영학부', departmentName: 'BUSINESS' },
  { department: '아동청소년학과', departmentName: 'CHILD_YOUTH' },
  { department: '공공인재학부', departmentName: 'PUBLIC' },
  { department: '군사학과', departmentName: 'MILITARY' },
  { department: '중어전공', departmentName: 'CHINESE' },
  { department: '일어전공', departmentName: 'JAPANESE' },
  { department: '이공대', departmentName: 'ENGINEERING' },
  { department: '금융정보공학과', departmentName: 'FINANCE' },
  { department: '나노화학생명공학과', departmentName: 'NANO_BIO' },
  { department: '토목건축공학과', departmentName: 'ARCHITECTURE' },
  { department: '소프트웨어학과', departmentName: 'SOFTWARE' },
  { department: '전자컴퓨터공학과', departmentName: 'ELECTRONIC_COMPUTER' },
  { department: '도시공학과', departmentName: 'URBAN' },
  { department: '물류시스템공학과', departmentName: 'LOGISTICS' },
  { department: '예술대', departmentName: 'ARTS' },
  { department: '영화영상학과', departmentName: 'FILM' },
  { department: '미용예술학부', departmentName: 'BEAUTY' },
  { department: '음악학부', departmentName: 'MUSIC' },
  { department: '실용음악학부', departmentName: 'PRACTICAL_MUSIC' },
  { department: '디자인학부(비디, 라디)', departmentName: 'DESIGN_VDLD' },
  { department: '디자인학부(VOID(보이드)/sesi)', departmentName: 'DESIGN_VOID' },
  { department: '광고홍보영상학과', departmentName: 'AD_PR' },
  { department: '융합대', departmentName: 'CONVERGENCE' },
  { department: '스포츠테크놀로지학과', departmentName: 'SPORTS_TECH' },
  { department: '미래융합대학1', departmentName: 'FUTURE_1' },
  { department: '미래융합대학2', departmentName: 'FUTURE_2' },
  { department: '총동아리연합회', departmentName: 'CLUB' },
  { department: '신문사', departmentName: 'PRESS' },
  { department: '축제기획단', departmentName: 'FESTIVAL_PLANNING' },
  { department: '학생처', departmentName: 'STUDENT_OFFICE' },
  { department: '총학생회', departmentName: 'STUDENT_COUNCIL' },
];
